### ISSUE TITLE
Suggestion: config workbench for add path in alias

### ISSUE THREAD

**Issue by radziksh** [andrew-lis/Workbench#2]
Hi, very useful extension, however I work with ReactJS project and there all files are components with this structure:
![screenshot_61](https://cloud.githubusercontent.com/assets/1275228/24453992/a74492a6-1492-11e7-95f1-8dabacf485f1.png)
 as you can see there is unclear which file I need:
![screenshot_62](https://cloud.githubusercontent.com/assets/1275228/24454054/f35c6bfa-1492-11e7-863f-1a687e1f4084.png)
of course I can fix alias directly in workbench file, but this is really annoying, is it possible configure extension for add folder name (or even full path) in alias automatically?

**Comment by andrew-lis** [comment]
Feature request accepted.
Implemented in version 1.0.5

**Comment by radziksh** [comment]
works well, thank you!
![screenshot_68](https://cloud.githubusercontent.com/assets/1275228/24497851/7300259c-1545-11e7-9882-32b802df698e.png)
