### ISSUE TITLE
Allow files outside of workspace to be added and used

### ISSUE THREAD

**Issue by boyangwang** [andrew-lis/Workbench#3]
Hi! Great extension, thanks!

I want to do a feature request (or maybe bug report) and I will be happy to submit a PR. The feature is this: if you add a file from outside of current workspace (that is, e.g. you added /etc/hosts to workbench), it will try to find from workbench and give warning: 

Ideally, it should respect absolute path in workbench.json. If it starts with a '/' or '~', as in `/etc/hosts`, resolve accordingly

![](https://img.alicdn.com/tfs/TB1N4A.mfDH8KJjy1XcXXcpdXXa-1392-414.png)

**Comment by tschofen** [comment]
+1

**Comment by andrew-lis** [comment]
@boyangwang -  I'm wondering whether there are any security issues with it, but meanwhile please submit a PR for this.

**Comment by boyangwang** [comment]
@andrew-lis With current implementation, I can work around by doing `../..`. So it's the same

PR will be ready soon

**Comment by boyangwang** [comment]
See #4

**Comment by boyangwang** [comment]
@andrew-lis Hi, have you got time to check the PR? It's one line change

**Comment by andrew-lis** [comment]
I've seen it, but it will work only on Linux (and there are no brackets around return statement)

**Comment by andrew-lis** [comment]
Done
