### ISSUE TITLE
Can you please add  windows support?

### ISSUE THREAD

**Issue by jiming** [andrew-lis/Workbench#7]
For window, the absolute path is not convert correct, can you please fix it?

![image](https://user-images.githubusercontent.com/455978/57276489-62887b00-70d4-11e9-8265-6012d997226d.png)

**Comment by andrew-lis** [comment]
Well I use it only on Windows.
Your file path looks weird, though. 
The "workbench.json" should look like this:

```
{
	"currentWorkbench": {
		"files": [
			{
				"path": "src\\app.ts",
				"alias": " 1 src/app.ts"
			}
		]
	}
}
```

**Comment by jiming** [comment]
ok, thank you!
